import json

def build_markdown_report(report: dict) -> str:
    title = report.get("title") or "Trend Report"
    platform = report.get("platform") or "Unknown Platform"
    summary = report.get("summary") or "_No summary available_"
    background = report.get("platform_background") or "_No background available_"

    topics = report.get("trending_topics") or []
    sentiment = report.get("sentiment_analysis") or {}

    md = []
    md.append(f"# {title} — {platform}\n")

    # Summary
    md.append("## Summary\n")
    md.append(f"{summary}\n")

    # Platform Background
    md.append("## Platform Background\n")
    md.append(f"{background}\n")

    # Trending Topics
    md.append("## Trending Topics\n")

    if topics:
        for i, topic in enumerate(topics, 1):
            name = topic.get("name") or topic.get("title") or "Unknown Topic"
            desc = topic.get("description") or "_No description_"
            md.append(f"### {i}. {name}\n{desc}\n")
    else:
        md.append("_No trending topics available_\n")

    # Sentiment
    md.append("## Sentiment Analysis\n")

    if sentiment:
        for k, v in sentiment.items():
            md.append(f"- **{k.capitalize()}**: {v}%\n")
    else:
        md.append("_No sentiment data available_\n")

    md.append("\n---\nGenerated by Social Media Trend Analyzer\n")

    return "\n".join(md)
